apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-test
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts
      # version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: helm-test
        namespace: flux-system
      interval: 1m
#  values:
#    replicaCount: 2
