apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-depl
  name: {{ .Release.Name }}-nginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-depl
    spec:
      containers:
        - image: nginx:1.18.0
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
status: {}
