apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-depl
  name: {{ .Release.Name }}-nginx-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30010
  selector:
    app: nginx-depl
  type: NodePort
status:
  loadBalancer: {}
